# Generated by Django 3.2.19 on 2023-06-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designproducts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
